//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace clientsmvc.Models

{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {   
        [Display(Name ="Employee ID :")]
        public int personId { get; set; }
        [Display(Name = "First Name :")]
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int Age { get; set; }
        public string emailAddress { get; set; }
        public string password { get; set; }
        public string confirmPassword { get; set; }
    }
}
