//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APDP201_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string Cust_Id { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_Surname { get; set; }
        public string Cust_Addr { get; set; }
        public string Cust_Cell { get; set; }
        public Nullable<decimal> Cust_Bal { get; set; }
    }
}
