//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APDP201_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockitem
    {
        public string Item_Code { get; set; }
        public string Item_desc { get; set; }
        public string Item_Size { get; set; }
        public Nullable<decimal> Item_Cost { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> Selling { get; set; }

        public double calcVat()
        {
            return Convert.ToDouble(Item_Cost) * 0.15; 
        }

        public double calcSelling()
        {
            return Convert.ToDouble(Item_Cost) + calcVat();
        }
    }
}
