// <auto-generated />
namespace ModdingDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class death : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(death));
        
        string IMigrationMetadata.Id
        {
            get { return "202301251653466_death"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
