//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace workingapplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class work
    {
        public int employee_id { get; set; }
        public string employee_name { get; set; }
        public string employee_job_type { get; set; }
        public Nullable<int> employee_rate_per_hour { get; set; }
        public Nullable<int> employee_work_days { get; set; }
    }
}
