// <auto-generated />
namespace Migrations_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_genre_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_genre_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202301260724498_added_genre_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
