// <auto-generated />
namespace GymManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_Gender_models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Gender_models));
        
        string IMigrationMetadata.Id
        {
            get { return "202303131526228_User_Gender_models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
