//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace videotutmvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCKITEM
    {
        public int itemCode { get; set; }
        public string itemDesc { get; set; }
        public string itemSize { get; set; }
        public Nullable<decimal> itemCost { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> selling { get; set; }
    }
}
