// <auto-generated />
namespace RestuarantApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class url_prop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(url_prop));
        
        string IMigrationMetadata.Id
        {
            get { return "202303091940028_url_prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
