// <auto-generated />
namespace JobApplicationForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class job_pos_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(job_pos_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202302031254438_job_pos_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
